=== petrandreev/mojarra/jsf-api/doc/web-facelettaglibrary_2_0.xsd
<?xml version = "1.0" encoding = "UTF-8"?>

<!--
 DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

 Copyright 1997-2007 Sun Microsystems, Inc. All rights reserved.

 The contents of this file are subject to the terms of either the GNU
 General Public License Version 2 only ("GPL") or the Common Development
 and Distribution License("CDDL") (collectively, the "License").  You
 may not use this file except in compliance with the License. You can obtain
 a copy of the License at https://glassfish.dev.java.net/public/CDDL+GPL.html
 or glassfish/bootstrap/legal/LICENSE.txt.  See the License for the specific
 language governing permissions and limitations under the License.

 When distributing the software, include this License Header Notice in each
 file and include the License file at glassfish/bootstrap/legal/LICENSE.txt.
 Sun designates this particular file as subject to the "Classpath" exception
 as provided by Sun in the GPL Version 2 section of the License file that
 accompanied this code.  If applicable, add the following below the License
 Header, with the fields enclosed by brackets [] replaced by your own
 identifying information: "Portions Copyrighted [year]
 [name of copyright owner]"

 Contributor(s):

 If you wish your version of this file to be governed by only the CDDL or
 only the GPL Version 2, indicate your decision by adding "[Contributor]
 elects to include this software in this distribution under the [CDDL or GPL
 Version 2] license."  If you don't indicate a single choice of license, a
 recipient has the option to distribute your version of this file under
 either the CDDL, the GPL Version 2 or to extend the choice of license to
 its licensees as provided above.  However, if you add GPL Version 2 code
 and therefore, elected the GPL Version 2 license, then the option applies
 only if the new code is made subject to such option by the copyright
 holder.
-->
<xsd:schema
     targetNamespace="http://java.sun.com/xml/ns/javaee"
     xmlns:javaee="http://java.sun.com/xml/ns/javaee"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     elementFormDefault="qualified"
     attributeFormDefault="unqualified"
     version="2.0">
    <xsd:include schemaLocation="javaee_5.xsd"/>
    <xsd:element name="facelet-taglib" type="javaee:facelet-taglibType">
        <xsd:unique name="facelet-taglib-tagname-uniqueness">
            <xsd:annotation>
                <xsd:documentation>

                    tag-names must be unique within a document.
                </xsd:documentation>
            </xsd:annotation>
            <xsd:selector xpath="javaee:tag"/>
            <xsd:field    xpath="javaee:tag-name"/>
        </xsd:unique>
        <xsd:unique name="faces-config-converter-ID-uniqueness">
            <xsd:annotation>
                <xsd:documentation>

                    Converter IDs must be unique within a document.
                </xsd:documentation>
            </xsd:annotation>
            <xsd:selector xpath="javaee:converter"/>
            <xsd:field    xpath="javaee:converter-id"/>
        </xsd:unique>
        <xsd:unique name="faces-config-validator-ID-uniqueness">
            <xsd:annotation>
                <xsd:documentation>

                    Validator IDs must be unique within a document.
                </xsd:documentation>
            </xsd:annotation>
            <xsd:selector xpath="javaee:validator"/>
            <xsd:field    xpath="javaee:validator-id"/>
        </xsd:unique>
    </xsd:element>
    <xsd:complexType name="facelet-taglibType">
        <xsd:choice>
            <xsd:sequence>
                <xsd:element name="library-class" 
                             type="javaee:fully-qualified-classType"/>
            </xsd:sequence>
            <xsd:sequence>
                <xsd:choice>
                    <xsd:sequence>
                        <xsd:element name="namespace" type="javaee:string"/>
                        <xsd:choice maxOccurs="unbounded">
                            <xsd:element name="tag" 
                                     type="javaee:facelet-taglib-tagType"/>
                            <xsd:element name="function"
                                     type="javaee:facelet-taglib-functionType"/>
                            <xsd:element name="resource"
                                     type="javaee:facelet-taglib-resourceType"/>
                        </xsd:choice>
                    </xsd:sequence>
                    <xsd:sequence>
                        <xsd:element name="namespace" type="javaee:string"/>
                        <xsd:element name="composite-library-name" 
                                 type="javaee:fully-qualified-classType"/>
                    </xsd:sequence>
                </xsd:choice>
            </xsd:sequence>
        </xsd:choice>
        <xsd:attribute name = "id" type = "xsd:ID"/>
        <xsd:attribute name="version"
                type="javaee:facelet-taglib-versionType"
                use="required"/>
    </xsd:complexType>
    <xsd:complexType name="facelet-taglib-tagType">
        <xsd:sequence>
            <xsd:element name="tag-name" type="javaee:string"/>
            <xsd:element name="handler-class"
                             type="javaee:fully-qualified-classType"
                             minOccurs="0" maxOccurs="1"/>
            <xsd:choice minOccurs="0" maxOccurs="1">
                <xsd:element name="component"
                                 type="javaee:facelet-taglib-tag-componentType"/>
                <xsd:element name="converter"
                                 type="javaee:facelet-taglib-tag-converterType"/>
                <xsd:element name="validator"
                                 type="javaee:facelet-taglib-tag-validatorType"/>
                <xsd:element name="source" type="javaee:string"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="facelet-taglib-functionType">
        <xsd:sequence>
            <xsd:element name="function-name" type="javaee:string"/>
            <xsd:element name="function-class" 
                             type="javaee:fully-qualified-classType"/>
            <xsd:element name="function-signature" type="javaee:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="facelet-taglib-resourceType">
        <xsd:sequence>
            <xsd:element name="mime-type" type="javaee:string" 
                             minOccurs="0" maxOccurs="1"/>
            <xsd:element name="resource-path" type="javaee:string"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="facelet-taglib-tag-componentType">
        <xsd:sequence>
            <xsd:element name="component-type" type="javaee:string"/>
            <xsd:element name="renderer-type" type="javaee:string"
                             minOccurs="0" maxOccurs="1"/>
            <xsd:element name="handler-class" type="javaee:fully-qualified-classType"
                             minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="facelet-taglib-tag-converterType">
        <xsd:sequence>
            <xsd:element name="converter-id" type="javaee:string"/>
            <xsd:element name="handler-class" 
                             type="javaee:fully-qualified-classType"
                             minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="facelet-taglib-tag-validatorType">
        <xsd:sequence>
            <xsd:element name="validator-id" type="javaee:string"/>
            <xsd:element name="handler-class" 
                             type="javaee:fully-qualified-classType"
                             minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    
    <!-- **************************************************** -->
    <xsd:simpleType name="facelet-taglib-versionType">
        <xsd:annotation>
            <xsd:documentation>

                This type contains the recognized versions of
                facelet-taglib supported.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="2.0"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== petrandreev/mojarra/jsf-ri/systest-per-webapp/process-as-jspx/web/WEB-INF/jspx.taglib.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

    Copyright (c) 1997-2010 Oracle and/or its affiliates. All rights reserved.

    The contents of this file are subject to the terms of either the GNU
    General Public License Version 2 only ("GPL") or the Common Development
    and Distribution License("CDDL") (collectively, the "License").  You
    may not use this file except in compliance with the License.  You can
    obtain a copy of the License at
    https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
    or packager/legal/LICENSE.txt.  See the License for the specific
    language governing permissions and limitations under the License.

    When distributing the software, include this License Header Notice in each
    file and include the License file at packager/legal/LICENSE.txt.

    GPL Classpath Exception:
    Oracle designates this particular file as subject to the "Classpath"
    exception as provided by Oracle in the GPL Version 2 section of the License
    file that accompanied this code.

    Modifications:
    If applicable, add the following below the License Header, with the fields
    enclosed by brackets [] replaced by your own identifying information:
    "Portions Copyright [year] [name of copyright owner]"

    Contributor(s):
    If you wish your version of this file to be governed by only the CDDL or
    only the GPL Version 2, indicate your decision by adding "[Contributor]
    elects to include this software in this distribution under the [CDDL or GPL
    Version 2] license."  If you don't indicate a single choice of license, a
    recipient has the option to distribute your version of this file under
    either the CDDL, the GPL Version 2 or to extend the choice of license to
    its licensees as provided above.  However, if you add GPL Version 2 code
    and therefore, elected the GPL Version 2 license, then the option applies
    only if the new code is made subject to such option by the copyright
    holder.

-->

<facelet-taglib xmlns="http://java.sun.com/xml/ns/javaee"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-facelettaglibrary_2_0.xsd"
              version="2.0">
    <namespace>http://java.sun.com/JSP/Page</namespace>

    <!-- http://java.sun.com/products/jsp/syntax/1.2/syntaxref12.html -->  
    <tag>
        <tag-name>root</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>directive.page</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.PageDirectiveHandler</handler-class>
    </tag>
    <tag>
        <tag-name>directive.include</tag-name>
        <handler-class>com.sun.faces.facelets.tag.ui.IncludeHandler</handler-class>
    </tag>
    <tag>
        <tag-name>include</tag-name>
        <handler-class>com.sun.faces.facelets.tag.ui.IncludeHandler</handler-class>
    </tag>
    <tag>
        <tag-name>declaration</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>expression</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>scriptlet</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>text</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>forward</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>param</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.ParamHandler</handler-class>
    </tag>
    <tag>
        <tag-name>params</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>plugin</tag-name>
        <component>
            <component-type>javax.faces.Output</component-type>
            <renderer-type>jsp.Plugin</renderer-type>
        </component>
    </tag>
    <tag>
        <tag-name>params</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>fallback</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>setProperty</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
    <tag>
        <tag-name>useBean</tag-name>
        <handler-class>com.sun.faces.facelets.tag.jsp.DummyTagHandler</handler-class>
    </tag>
</facelet-taglib>

=== petrandreev/mojarra/2.2.8/test/servlet30/dynamic/src/main/webapp/WEB-INF/dynamic.taglib.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

    DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

    Copyright (c) 1997-2014 Oracle and/or its affiliates. All rights reserved.

    The contents of this file are subject to the terms of either the GNU
    General Public License Version 2 only ("GPL") or the Common Development
    and Distribution License("CDDL") (collectively, the "License").  You
    may not use this file except in compliance with the License.  You can
    obtain a copy of the License at
    https://glassfish.dev.java.net/public/CDDL+GPL_1_1.html
    or packager/legal/LICENSE.txt.  See the License for the specific
    language governing permissions and limitations under the License.

    When distributing the software, include this License Header Notice in each
    file and include the License file at packager/legal/LICENSE.txt.

    GPL Classpath Exception:
    Oracle designates this particular file as subject to the "Classpath"
    exception as provided by Oracle in the GPL Version 2 section of the License
    file that accompanied this code.

    Modifications:
    If applicable, add the following below the License Header, with the fields
    enclosed by brackets [] replaced by your own identifying information:
    "Portions Copyright [year] [name of copyright owner]"

    Contributor(s):
    If you wish your version of this file to be governed by only the CDDL or
    only the GPL Version 2, indicate your decision by adding "[Contributor]
    elects to include this software in this distribution under the [CDDL or GPL
    Version 2] license."  If you don't indicate a single choice of license, a
    recipient has the option to distribute your version of this file under
    either the CDDL, the GPL Version 2 or to extend the choice of license to
    its licensees as provided above.  However, if you add GPL Version 2 code
    and therefore, elected the GPL Version 2 license, then the option applies
    only if the new code is made subject to such option by the copyright
    holder.

-->

<facelet-taglib xmlns="http://java.sun.com/xml/ns/javaee"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-facelettaglibrary_2_0.xsd" 
                version="2.0">
    <namespace>http://www.oracle.com/mojarra/test/dynamic</namespace>
    <tag>
        <tag-name>toggleComponent</tag-name>
        <component>
            <component-type>com.sun.faces.test.servlet30.dynamic.ToggleComponent</component-type>
        </component>
    </tag>
    <tag>
        <tag-name>addcomponent</tag-name>
        <component>
            <component-type>com.sun.faces.test.servlet30.dynamic.AddComponent</component-type>
        </component>
    </tag>
    <tag>
        <tag-name>stablecomponent</tag-name>
        <component>
            <component-type>com.sun.faces.test.servlet30.dynamic.StableComponent</component-type>
        </component>
    </tag>
    <tag>
        <tag-name>tablecomponent</tag-name>
        <component>
            <component-type>com.sun.faces.test.servlet30.dynamic.TableComponent</component-type>
        </component>
    </tag>
    <tag>
        <tag-name>recursivecomponent</tag-name>
        <component>
            <component-type>com.sun.faces.test.servlet30.dynamic.RecursiveComponent</component-type>
        </component>
    </tag>
    <tag>
        <tag-name>addcomponent1</tag-name>
        <component>
            <component-type>com.sun.faces.test.servlet30.dynamic.AddComponent1</component-type>
        </component>
    </tag>
    <tag>
        <tag-name>movecomponent</tag-name>
        <component>
            <component-type>com.sun.faces.test.servlet30.dynamic.MoveComponent</component-type>
        </component>
    </tag>
    <tag>
        <tag-name>movecomponent2</tag-name>
        <component>
            <component-type>com.sun.faces.test.servlet30.dynamic.MoveComponent2</component-type>
        </component>
    </tag>
</facelet-taglib>
